[package]
name = "muen_rs"
version = "0.1.0"
edition = "2024"

[features]

[profile.dev]
panic="abort"

[profile.release]
panic="abort"

[lib]
crate-type=["staticlib"]

[dependencies]
x86_64 = "0.15.2"
